version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo "Installing Docker Compose"
      - curl -L https://github.com/docker/compose/releases/download/1.28.6/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
      - chmod +x /usr/local/bin/docker-compose

  build:
    commands:
      - echo "Building nginx container"
      - cd nginx
      - docker-compose build

  post_build:
    commands:
      - echo "Pushing nginx container to Amazon ECR"
      - $(aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION})
      - docker tag nginx ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/nginx
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/nginx
